// ----------------------------------------------------------------------
// AI Learning Path Generation Types
// ----------------------------------------------------------------------

import type { IAiProgram } from './ai-program-generation';
import type { IAiCourse, AiProviderType } from './ai-course';
import type { IAiProvider, IAiProviderModel } from './ai-provider';

// ----------------------------------------------------------------------
// Shared provider config passed from the main toolbar to all panels
// ----------------------------------------------------------------------

export interface ILPProviderConfig {
  /** Text provider */
  textProvider: IAiProvider | null | undefined;
  /** Text model */
  textModel: IAiProviderModel | null | undefined;
  /** Image provider */
  imageProvider: IAiProvider | undefined;
  /** Image model */
  imageModel: IAiProviderModel | undefined;
  /** Video provider */
  videoProvider: IAiProvider | undefined;
  /** Video model */
  videoModel: IAiProviderModel | undefined;
  /** Temperature */
  temperature: number;
  /** Proprietary video: duration per scene */
  proprietaryDurationScenes: number;
  /** Proprietary video: number of scenes */
  proprietaryScenesNumber: number;
  /** Proprietary video: image model */
  proprietaryImageModel: string;
  /** Whether providers are loading */
  isLoadingProviders: boolean;
  /** Get legacy provider type string */
  getLegacyProviderType: (provider: IAiProvider) => AiProviderType;
}

// ----------------------------------------------------------------------
// Learning Path Instruction JSON Structure
// (Generated by AI from user's prompt)
// ----------------------------------------------------------------------

/**
 * Course instruction within a program
 */
export interface ILPCourseInstruction {
  instruction_c: string;
}

/**
 * Program instruction within a learning path
 */
export interface ILPProgramInstruction {
  instruction_pg: string;
  courses: ILPCourseInstruction[];
}

/**
 * Top-level learning path instruction
 */
export interface ILPLearningPathInstruction {
  instruction_lp: string;
  programs: ILPProgramInstruction[];
}

/**
 * Root JSON structure generated by AI
 */
export interface ILPInstructionJSON {
  learning_path: ILPLearningPathInstruction;
}

// ----------------------------------------------------------------------
// Course generation tracking
// ----------------------------------------------------------------------

/**
 * A generated course with its persisted rowId and program reference
 */
export interface ILPGeneratedCourse {
  /** The rowId returned by SaveOrUpdateAiCourseGenerationService */
  rowId: string;
  /** Index of the program this course belongs to */
  programIndex: number;
  /** Index of the course within its program */
  courseIndex: number;
  /** Original instruction used to generate this course */
  instruction_c: string;
  /** The full generated course data from AI */
  courseData: IAiCourse;
  /** Generation status */
  status: 'pending' | 'generating' | 'completed' | 'error';
  /** Error message if generation failed */
  error?: string;
}

// ----------------------------------------------------------------------
// Program generation tracking
// ----------------------------------------------------------------------

/**
 * A generated program with its persisted rowId and learning path reference
 */
export interface ILPGeneratedProgram {
  /** The rowId returned by SaveOrUpdateAiProgramService */
  rowId: string;
  /** Index of the program in the instruction JSON */
  programIndex: number;
  /** Original instruction used to generate this program */
  instruction_pg: string;
  /** The courseLmsIds (rowIds) of courses belonging to this program */
  courseRowIds: string[];
  /** The full generated program data from AI */
  programData: Partial<IAiProgram>;
  /** Generation status */
  status: 'pending' | 'generating' | 'completed' | 'error';
  /** Error message if generation failed */
  error?: string;
}

/**
 * State for the entire learning path generation process
 */
export interface ILPGenerationState {
  /** Step 1: The instruction JSON from AI */
  instructionJSON: ILPInstructionJSON | null;
  /** Step 2: All generated courses with their rowIds */
  generatedCourses: ILPGeneratedCourse[];
  /** Step 3: All generated programs with their rowIds */
  generatedPrograms: ILPGeneratedProgram[];
  /** Overall generation status */
  status: 'idle' | 'generating-instructions' | 'generating-courses' | 'generating-programs' | 'completed' | 'error';
  /** Number of courses completed */
  coursesCompleted: number;
  /** Total number of courses to generate */
  coursesTotal: number;
  /** Number of programs completed */
  programsCompleted: number;
  /** Total number of programs to generate */
  programsTotal: number;
}
