
export const ALL_COLUMNS = [
  { id: 'nomenclature', label: 'Nomenclatura' },
  { id: 'name', label: 'Nombre' },
  { id: 'description', label: 'Descripción' },
  { id: 'result', label: 'Resultado' },
  { id: 'requiresOLA', label: 'Requiere OLA' },
  { id: 'periodicity', label: 'Periodicidad' },
  { id: 'workload', label: 'Carga de Trabajo' },
  { id: 'cost', label: 'Costo' },
  { id: 'context', label: 'Contexto' },
  { id: 'status', label: 'Estado' },
  { id: 'startDate', label: 'Fecha de Inicio' },
  { id: 'endDate', label: 'Fecha de Fin' },
  { id: 'scheduleTask', label: 'Tarea Programada' },
  { id: 'projectStatus', label: 'Estado del Proyecto' },
  { id: 'taskType', label: 'Tipo de Tarea' },
  { id: 'taskDeadline', label: 'Fecha Límite' },
  { id: 'taskStartDate', label: 'Fecha Inicio Tarea' },
  { id: 'taskUpdateDate', label: 'Fecha Actualización Tarea' },
  { id: 'fulfillmentAction', label: 'Acción de Cumplimiento' },
  { id: 'reminder', label: 'Recordatorio' },
  { id: 'sistemRequirement', label: 'Requerimiento del Sistema' },
  { id: 'superiorProcess', label: 'Proceso Superior' },
  { id: 'processType', label: 'Tipo de Proceso' },
  { id: 'period', label: 'Periodo' },
  { id: 'timeUnit', label: 'Unidad de Tiempo' },
  { id: 'createdBy', label: 'Creado Por' },
  { id: 'createdDate', label: 'Fecha de Creación' },
  { id: 'lastModifiedBy', label: 'Modificado Por' },
  { id: 'lastModifiedDate', label: 'Fecha de Modificación' },
];

export const DEFAULT_COLUMNS = ['nomenclature', 'name', 'description', 'requiresOLA', 'periodicity'];
