
export const ALL_COLUMNS = [
  { id: 'nomenclature', label: 'process.table.table.columns.nomenclature' },
  { id: 'name', label: 'process.table.table.columns.name' },
  { id: 'description', label: 'process.table.table.columns.description' },
  { id: 'result', label: 'process.table.table.columns.result' },
  { id: 'requiresOLA', label: 'process.table.table.columns.requiresOLA' },
  { id: 'periodicity', label: 'process.table.table.columns.periodicity' },
  { id: 'workload', label: 'process.table.table.columns.workload' },
  { id: 'cost', label: 'process.table.table.columns.cost' },
  { id: 'context', label: 'process.table.table.columns.context' },
  { id: 'status', label: 'process.table.table.columns.status' },
  { id: 'startDate', label: 'process.table.table.columns.startDate' },
  { id: 'endDate', label: 'process.table.table.columns.endDate' },
  { id: 'scheduleTask', label: 'process.table.table.columns.scheduleTask' },
  { id: 'projectStatus', label: 'process.table.table.columns.projectStatus' },
  { id: 'taskType', label: 'process.table.table.columns.taskType' },
  { id: 'taskDeadline', label: 'process.table.table.columns.taskDeadline' },
  { id: 'taskStartDate', label: 'process.table.table.columns.taskStartDate' },
  { id: 'taskUpdateDate', label: 'process.table.table.columns.taskUpdateDate' },
  { id: 'fulfillmentAction', label: 'process.table.table.columns.fulfillmentAction' },
  { id: 'reminder', label: 'process.table.table.columns.reminder' },
  { id: 'sistemRequirement', label: 'process.table.table.columns.sistemRequirement' },
  { id: 'superiorProcess', label: 'process.table.table.columns.superiorProcess' },
  { id: 'processType', label: 'process.table.table.columns.processType' },
  { id: 'period', label: 'process.table.table.columns.period' },
  { id: 'timeUnit', label: 'process.table.table.columns.timeUnit' },
  { id: 'createdBy', label: 'process.table.table.columns.createdBy' },
  { id: 'createdDate', label: 'process.table.table.columns.createdDate' },
  { id: 'lastModifiedBy', label: 'process.table.table.columns.lastModifiedBy' },
  { id: 'lastModifiedDate', label: 'process.table.table.columns.lastModifiedDate' },
];

export const DEFAULT_COLUMNS = ['nomenclature', 'name', 'description', 'requiresOLA', 'periodicity'];
