
export const ALL_COLUMNS = [
  { id: 'code', label: 'Código' },
  { id: 'name', label: 'Nombre' },
  { id: 'jobType', label: 'Tipo de Puesto' },
  { id: 'objectives', label: 'Objetivos' },
  { id: 'expectedResults', label: 'Resultados Esperados' },
  { id: 'requirements', label: 'Requisitos' },
  { id: 'otherFunctions', label: 'Otras Funciones' },
  { id: 'minimumAcademicLevel', label: 'Nivel Académico Mínimo' },
  { id: 'desiredAcademicLevel', label: 'Nivel Académico Deseado' },
  { id: 'minimumExperience', label: 'Experiencia Mínima' },
  { id: 'desiredExperience', label: 'Experiencia Deseada' },
  { id: 'supervises', label: 'Supervisa a' },
  { id: 'regionalLocation', label: 'Ubicación Regional' },
  { id: 'headquarters', label: 'Sede' },
  { id: 'version', label: 'Versión' },
  { id: 'createdAt', label: 'Fecha de Creación' },
  { id: 'superiorJob', label: 'Puesto Superior' },
  { id: 'numberOfPositions', label: 'Número de Plazas' },
  { id: 'numberOfHoursPerPosition', label: 'Horas por Plaza' },
  { id: 'academicProfile', label: 'Perfil Académico' },
  { id: 'psychologicalProfile', label: 'Perfil Psicológico' },
  { id: 'internalRelationship', label: 'Relaciones Internas' },
  { id: 'externalRelationship', label: 'Relaciones Externas' },
  { id: 'competencies', label: 'Competencias' },
  { id: 'actorStatus', label: 'Estado' },
];

export const DEFAULT_COLUMNS = ['code', 'name', 'jobType'];
