
export const ALL_COLUMNS = [
  { id: 'code', label: 'positions.table.code' },
  { id: 'name', label: 'positions.table.name' },
  { id: 'jobType', label: 'positions.table.jobType' },
  { id: 'objectives', label: 'positions.table.objectives' },
  { id: 'expectedResults', label: 'positions.table.expectedResults' },
  { id: 'requirements', label: 'positions.table.requirements' },
  { id: 'otherFunctions', label: 'positions.table.otherFunctions' },
  { id: 'minimumAcademicLevel', label: 'positions.table.minimumAcademicLevel' },
  { id: 'desiredAcademicLevel', label: 'positions.table.desiredAcademicLevel' },
  { id: 'minimumExperience', label: 'positions.table.minimumExperience' },
  { id: 'desiredExperience', label: 'positions.table.desiredExperience' },
  { id: 'supervises', label: 'positions.table.supervises' },
  { id: 'regionalLocation', label: 'positions.table.regionalLocation' },
  { id: 'headquarters', label: 'positions.table.headquarters' },
  { id: 'version', label: 'positions.table.version' },
  { id: 'createdAt', label: 'positions.table.createdAt' },
  { id: 'superiorJob', label: 'positions.table.superiorJob' },
  { id: 'numberOfPositions', label: 'positions.table.numberOfPositions' },
  { id: 'numberOfHoursPerPosition', label: 'positions.table.numberOfHoursPerPosition' },
  { id: 'academicProfile', label: 'positions.table.academicProfile' },
  { id: 'psychologicalProfile', label: 'positions.table.psychologicalProfile' },
  { id: 'internalRelationship', label: 'positions.table.internalRelationship' },
  { id: 'externalRelationship', label: 'positions.table.externalRelationship' },
  { id: 'competencies', label: 'positions.table.competencies' },
  { id: 'actorStatus', label: 'positions.table.actorStatus' },
];

export const DEFAULT_COLUMNS = ['code', 'name', 'jobType'];
