import { NextResponse } from 'next/server';

export const runtime = 'edge';

export async function GET() {
  const data = [
    [
      {
        "createdBy": null,
        "createdDate": "2025-11-19T20:31:17.644Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-11-19T20:31:17.644Z",
        "id": 1,
        "name": "ads",
        "description": "adf",
        "startDate": "2023-01-01",
        "endDate": "2023-01-01",
        "measurementForm": "sfa",
        "consequencesOfNotAchieving": "afaf",
        "objectiveLevel": 2,
        "code": "asf",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-17T04:10:18.883Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-17T04:10:18.883Z",
        "id": 3,
        "name": "Aumentar ventas",
        "description": "Incrementar ventas anuales",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Porcentaje",
        "consequencesOfNotAchieving": "DisminuciÃ³n de ingresos",
        "objectiveLevel": null,
        "code": "OBJ-001",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-17T04:10:18.883Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-17T04:10:18.883Z",
        "id": 4,
        "name": "Mejorar calidad",
        "description": "Reducir defectos",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Indicador",
        "consequencesOfNotAchieving": "Clientes insatisfechos",
        "objectiveLevel": null,
        "code": "OBJ-002",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-20T03:28:42.138Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-20T03:28:42.138Z",
        "id": 5,
        "name": "Aumentar ventas",
        "description": "Incrementar ventas anuales",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Porcentaje",
        "consequencesOfNotAchieving": "DisminuciÃ³n de ingresos",
        "objectiveLevel": null,
        "code": "OBJ-001",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-20T03:28:42.138Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-20T03:28:42.138Z",
        "id": 6,
        "name": "Mejorar calidad",
        "description": "Reducir defectos",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Indicador",
        "consequencesOfNotAchieving": "Clientes insatisfechos",
        "objectiveLevel": null,
        "code": "OBJ-002",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-20T03:28:42.138Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-20T03:28:42.138Z",
        "id": 7,
        "name": "Mejorar calidad CREATE TEST",
        "description": "Reducir defectos MELO",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Indicador",
        "consequencesOfNotAchieving": "Clientes insatisfechos MUCHOS",
        "objectiveLevel": null,
        "code": "OBJ-002",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-20T03:31:40.888Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-20T03:31:40.888Z",
        "id": 8,
        "name": "Bajar ventas UPDATE TEST",
        "description": "Decrementar ventas anuales",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Porcentaje",
        "consequencesOfNotAchieving": "DisminuciÃ³n de ingresos",
        "objectiveLevel": null,
        "code": "OBJ-001",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      },
      {
        "createdBy": null,
        "createdDate": "2025-12-20T03:31:40.888Z",
        "lastModifiedBy": null,
        "lastModifiedDate": "2025-12-20T03:31:40.888Z",
        "id": 9,
        "name": "Empeorar calidad UPDATE TEST",
        "description": "Reducir defectos",
        "startDate": "1969-12-31",
        "endDate": "1969-12-31",
        "measurementForm": "Indicador",
        "consequencesOfNotAchieving": "Clientes insatisfechos",
        "objectiveLevel": null,
        "code": "OBJ-002",
        "participantId": null,
        "superiorObjective": null,
        "objectiveType": null
      }
    ],
    14
  ];

  return NextResponse.json(data);
}
