export const MOCK_ORGANIZATIONAL_DATA = {
  root: {
    id: '1',
    positionId: 'pos-ceo-001',
    name: 'Chief Executive Officer',
    positionCode: 'CEO',
    positionImage: null,
    organizationId: 'org-1',
    organizationName: 'Meta Headquarters',
    organizationColor: '#1877f2',
    functionalArea: 'Executive Leadership',
    location: 'sede-principal',
    hierarchicalLevel: 'alta_direccion',
    requiredEmployees: 1,
    vacancies: 0,
    
    parentPositionId: null,
    parentPositionName: null,
    
    description: 'Chief Executive Officer responsible for overall company strategy and vision',
    skills: ['Strategic Leadership', 'Business Vision', 'Innovation', 'Global Management'],
    isManagerial: true,
    assignedEmployees: [
      {
        id: 'emp-1',
        firstName: 'Mark',
        firstLastName: 'Zuckerberg',
        email: 'mark.zuckerberg@meta.com',
        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-1.webp',
        isActive: true,
      }
    ],
    children: [
      {
        id: '2',
        positionId: 'pos-cto-001',
        name: 'Chief Technology Officer',
        positionCode: 'CTO',
        positionImage: null,
        organizationId: 'org-1',
        organizationName: 'Meta Headquarters',
        organizationColor: '#1877f2',
        functionalArea: 'Engineering & Technology',
        location: 'sede-principal',
        hierarchicalLevel: 'alta_direccion',
        requiredEmployees: 1,
        vacancies: 0,
        
        parentPositionId: '1',
        parentPositionName: 'Chief Executive Officer',
        
        description: 'Oversees all technology strategy and engineering operations',
        skills: ['Technical Architecture', 'Engineering Leadership', 'Innovation', 'Scalability'],
        isManagerial: true,
        assignedEmployees: [
          {
            id: 'emp-2',
            firstName: 'Andrew',
            firstLastName: 'Bosworth',
            email: 'andrew.bosworth@meta.com',
            avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-2.webp',
            isActive: true,
          }
        ],
        children: [
          {
            id: '3',
            positionId: 'pos-vp-infra-001',
            name: 'VP of Infrastructure',
            positionCode: 'VP-INFRA',
            positionImage: null,
            organizationId: 'org-2',
            organizationName: 'Engineering Division',
            organizationColor: '#00a400',
            functionalArea: 'Infrastructure Engineering',
            location: 'sede-principal',
            hierarchicalLevel: 'gerencial',
            requiredEmployees: 1,
            vacancies: 0,
            
            parentPositionId: '2',
            parentPositionName: 'Chief Technology Officer',
            
            description: 'Leads infrastructure and platform engineering teams',
            skills: ['Distributed Systems', 'Cloud Architecture', 'DevOps', 'Site Reliability'],
            isManagerial: true,
            assignedEmployees: [
              {
                id: 'emp-3',
                firstName: 'Sarah',
                firstLastName: 'Chen',
                email: 'sarah.chen@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-3.webp',
                isActive: true,
              }
            ],
            children: [
              {
                id: '4',
                positionId: 'pos-eng-mgr-infra-001',
                name: 'Engineering Manager - Infrastructure',
                positionCode: 'EM-INFRA',
                positionImage: null,
                organizationId: 'org-2',
                organizationName: 'Engineering Division',
                organizationColor: '#00a400',
                functionalArea: 'Infrastructure Engineering',
                location: 'sede-principal',
                hierarchicalLevel: 'ejecutivo',
                requiredEmployees: 2,
                vacancies: 1,
                
                parentPositionId: '3',
                parentPositionName: 'VP of Infrastructure',
                
                description: 'Manages infrastructure engineering team and delivery',
                skills: ['Team Leadership', 'Kubernetes', 'AWS', 'Performance Optimization'],
                isManagerial: true,
                assignedEmployees: [
                  {
                    id: 'emp-4',
                    firstName: 'Michael',
                    firstLastName: 'Rodriguez',
                    email: 'michael.rodriguez@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-4.webp',
                    isActive: true,
                  }
                ],
                children: [
                  {
                    id: '5',
                    positionId: 'pos-sre-001',
                    name: 'Site Reliability Engineer',
                    positionCode: 'SRE',
                    positionImage: null,
                    organizationId: 'org-2',
                    organizationName: 'Engineering Division',
                    organizationColor: '#00a400',
                    functionalArea: 'Infrastructure Engineering',
                    location: 'sede-principal',
                    hierarchicalLevel: 'operativo',
                    requiredEmployees: 8,
                    vacancies: 2,
                    
                    parentPositionId: '4',
                    parentPositionName: 'Engineering Manager - Infrastructure',
                    
                    description: 'Ensures reliability and performance of production systems',
                    skills: ['Linux', 'Python', 'Monitoring', 'Incident Response'],
                    isManagerial: false,
                    assignedEmployees: [
                      {
                        id: 'emp-5',
                        firstName: 'David',
                        firstLastName: 'Kim',
                        email: 'david.kim@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-5.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-6',
                        firstName: 'Jessica',
                        firstLastName: 'Martinez',
                        email: 'jessica.martinez@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-6.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-7',
                        firstName: 'Ryan',
                        firstLastName: 'Thompson',
                        email: 'ryan.thompson@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-7.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-8',
                        firstName: 'Emily',
                        firstLastName: 'Wang',
                        email: 'emily.wang@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-8.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-9',
                        firstName: 'James',
                        firstLastName: 'Anderson',
                        email: 'james.anderson@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-9.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-10',
                        firstName: 'Sophia',
                        firstLastName: 'Lee',
                        email: 'sophia.lee@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-10.webp',
                        isActive: true,
                      }
                    ],
                    children: undefined,
                  }
                ],
              }
            ],
          },
          {
            id: '6',
            positionId: 'pos-vp-ai-001',
            name: 'VP of AI Research',
            positionCode: 'VP-AI',
            positionImage: null,
            organizationId: 'org-2',
            organizationName: 'Engineering Division',
            organizationColor: '#00a400',
            functionalArea: 'AI & Machine Learning',
            location: 'sede-principal',
            hierarchicalLevel: 'gerencial',
            requiredEmployees: 1,
            vacancies: 0,
            
            parentPositionId: '2',
            parentPositionName: 'Chief Technology Officer',
            
            description: 'Leads AI research and machine learning initiatives',
            skills: ['Machine Learning', 'Deep Learning', 'Research Leadership', 'AI Strategy'],
            isManagerial: true,
            assignedEmployees: [
              {
                id: 'emp-11',
                firstName: 'Yann',
                firstLastName: 'LeCun',
                email: 'yann.lecun@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-11.webp',
                isActive: true,
              }
            ],
            children: [
              {
                id: '7',
                positionId: 'pos-ml-eng-001',
                name: 'Machine Learning Engineer',
                positionCode: 'ML-ENG',
                positionImage: null,
                organizationId: 'org-2',
                organizationName: 'Engineering Division',
                organizationColor: '#00a400',
                functionalArea: 'AI & Machine Learning',
                location: 'sede-principal',
                hierarchicalLevel: 'operativo',
                requiredEmployees: 6,
                vacancies: 3,
                
                parentPositionId: '6',
                parentPositionName: 'VP of AI Research',
                
                description: 'Develops and deploys machine learning models',
                skills: ['PyTorch', 'TensorFlow', 'NLP', 'Computer Vision'],
                isManagerial: false,
                assignedEmployees: [
                  {
                    id: 'emp-12',
                    firstName: 'Priya',
                    firstLastName: 'Sharma',
                    email: 'priya.sharma@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-12.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-13',
                    firstName: 'Alex',
                    firstLastName: 'Johnson',
                    email: 'alex.johnson@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-13.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-14',
                    firstName: 'Maria',
                    firstLastName: 'Garcia',
                    email: 'maria.garcia@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-14.webp',
                    isActive: true,
                  }
                ],
                children: undefined,
              }
            ],
          },
          {
            id: '8',
            positionId: 'pos-vp-product-eng-001',
            name: 'VP of Product Engineering',
            positionCode: 'VP-PROD-ENG',
            positionImage: null,
            organizationId: 'org-2',
            organizationName: 'Engineering Division',
            organizationColor: '#00a400',
            functionalArea: 'Product Engineering',
            location: 'sucursal-norte',
            hierarchicalLevel: 'gerencial',
            requiredEmployees: 1,
            vacancies: 0,
            
            parentPositionId: '2',
            parentPositionName: 'Chief Technology Officer',
            
            description: 'Oversees product engineering teams across all platforms',
            skills: ['Product Development', 'Mobile Engineering', 'Web Development', 'Team Scaling'],
            isManagerial: true,
            assignedEmployees: [
              {
                id: 'emp-15',
                firstName: 'Tom',
                firstLastName: 'Alison',
                email: 'tom.alison@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-15.webp',
                isActive: true,
              }
            ],
            children: [
              {
                id: '9',
                positionId: 'pos-eng-mgr-mobile-001',
                name: 'Engineering Manager - Mobile',
                positionCode: 'EM-MOBILE',
                positionImage: null,
                organizationId: 'org-2',
                organizationName: 'Engineering Division',
                organizationColor: '#00a400',
                functionalArea: 'Product Engineering',
                location: 'sucursal-norte',
                hierarchicalLevel: 'ejecutivo',
                requiredEmployees: 2,
                vacancies: 0,
                
                parentPositionId: '8',
                parentPositionName: 'VP of Product Engineering',
                
                description: 'Manages mobile engineering team for iOS and Android',
                skills: ['iOS Development', 'Android Development', 'React Native', 'Team Management'],
                isManagerial: true,
                assignedEmployees: [
                  {
                    id: 'emp-16',
                    firstName: 'Lisa',
                    firstLastName: 'Brown',
                    email: 'lisa.brown@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-16.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-17',
                    firstName: 'Kevin',
                    firstLastName: 'Davis',
                    email: 'kevin.davis@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-17.webp',
                    isActive: true,
                  }
                ],
                children: [
                  {
                    id: '10',
                    positionId: 'pos-ios-eng-001',
                    name: 'iOS Engineer',
                    positionCode: 'IOS-ENG',
                    positionImage: null,
                    organizationId: 'org-2',
                    organizationName: 'Engineering Division',
                    organizationColor: '#00a400',
                    functionalArea: 'Product Engineering',
                    location: 'sucursal-norte',
                    hierarchicalLevel: 'operativo',
                    requiredEmployees: 5,
                    vacancies: 1,
                    
                    parentPositionId: '9',
                    parentPositionName: 'Engineering Manager - Mobile',
                    
                    description: 'Develops iOS applications for Meta products',
                    skills: ['Swift', 'SwiftUI', 'Objective-C', 'iOS SDK'],
                    isManagerial: false,
                    assignedEmployees: [
                      {
                        id: 'emp-18',
                        firstName: 'Rachel',
                        firstLastName: 'Wilson',
                        email: 'rachel.wilson@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-18.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-19',
                        firstName: 'Daniel',
                        firstLastName: 'Moore',
                        email: 'daniel.moore@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-19.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-20',
                        firstName: 'Amanda',
                        firstLastName: 'Taylor',
                        email: 'amanda.taylor@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-20.webp',
                        isActive: true,
                      },
                      {
                        id: 'emp-21',
                        firstName: 'Chris',
                        firstLastName: 'Anderson',
                        email: 'chris.anderson@meta.com',
                        avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-21.webp',
                        isActive: true,
                      }
                    ],
                    children: undefined,
                  }
                ],
              }
            ],
          }
        ],
      },
      {
        id: '11',
        positionId: 'pos-cpo-001',
        name: 'Chief Product Officer',
        positionCode: 'CPO',
        positionImage: null,
        organizationId: 'org-3',
        organizationName: 'Product Division',
        organizationColor: '#ff6b35',
        functionalArea: 'Product Management',
        location: 'sede-principal',
        hierarchicalLevel: 'alta_direccion',
        requiredEmployees: 1,
        vacancies: 0,
        
        parentPositionId: '1',
        parentPositionName: 'Chief Executive Officer',
        
        description: 'Leads product strategy and vision across all Meta products',
        skills: ['Product Strategy', 'User Experience', 'Market Analysis', 'Innovation'],
        isManagerial: true,
        assignedEmployees: [
          {
            id: 'emp-22',
            firstName: 'Chris',
            firstLastName: 'Cox',
            email: 'chris.cox@meta.com',
            avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-22.webp',
            isActive: true,
          }
        ],
        children: [
          {
            id: '12',
            positionId: 'pos-dir-pm-001',
            name: 'Director of Product Management',
            positionCode: 'DIR-PM',
            positionImage: null,
            organizationId: 'org-3',
            organizationName: 'Product Division',
            organizationColor: '#ff6b35',
            functionalArea: 'Product Management',
            location: 'sede-principal',
            hierarchicalLevel: 'gerencial',
            requiredEmployees: 2,
            vacancies: 1,
            
            parentPositionId: '11',
            parentPositionName: 'Chief Product Officer',
            
            description: 'Directs product management teams and roadmap execution',
            skills: ['Product Roadmap', 'Stakeholder Management', 'Agile', 'Data Analysis'],
            isManagerial: true,
            assignedEmployees: [
              {
                id: 'emp-23',
                firstName: 'Jennifer',
                firstLastName: 'White',
                email: 'jennifer.white@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-23.webp',
                isActive: true,
              }
            ],
            children: [
              {
                id: '13',
                positionId: 'pos-pm-001',
                name: 'Product Manager',
                positionCode: 'PM',
                positionImage: null,
                organizationId: 'org-3',
                organizationName: 'Product Division',
                organizationColor: '#ff6b35',
                functionalArea: 'Product Management',
                location: 'sede-principal',
                hierarchicalLevel: 'ejecutivo',
                requiredEmployees: 8,
                vacancies: 2,
                
                parentPositionId: '12',
                parentPositionName: 'Director of Product Management',
                
                description: 'Manages product features and user experience',
                skills: ['Product Design', 'User Research', 'Analytics', 'Communication'],
                isManagerial: false,
                assignedEmployees: [
                  {
                    id: 'emp-24',
                    firstName: 'Brian',
                    firstLastName: 'Harris',
                    email: 'brian.harris@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-24.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-25',
                    firstName: 'Nicole',
                    firstLastName: 'Martin',
                    email: 'nicole.martin@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-1.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-26',
                    firstName: 'Steven',
                    firstLastName: 'Garcia',
                    email: 'steven.garcia@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-2.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-27',
                    firstName: 'Michelle',
                    firstLastName: 'Robinson',
                    email: 'michelle.robinson@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-3.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-28',
                    firstName: 'Jason',
                    firstLastName: 'Clark',
                    email: 'jason.clark@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-4.webp',
                    isActive: true,
                  },
                  {
                    id: 'emp-29',
                    firstName: 'Laura',
                    firstLastName: 'Lewis',
                    email: 'laura.lewis@meta.com',
                    avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-5.webp',
                    isActive: true,
                  }
                ],
                children: undefined,
              }
            ],
          }
        ],
      },
      {
        id: '14',
        positionId: 'pos-cfo-001',
        name: 'Chief Financial Officer',
        positionCode: 'CFO',
        positionImage: null,
        organizationId: 'org-4',
        organizationName: 'Finance Division',
        organizationColor: '#4a90e2',
        functionalArea: 'Finance & Operations',
        location: 'sede-principal',
        hierarchicalLevel: 'alta_direccion',
        requiredEmployees: 1,
        vacancies: 0,
        
        parentPositionId: '1',
        parentPositionName: 'Chief Executive Officer',
        
        description: 'Oversees financial planning, reporting, and operations',
        skills: ['Financial Strategy', 'Corporate Finance', 'Risk Management', 'Investor Relations'],
        isManagerial: true,
        assignedEmployees: [
          {
            id: 'emp-30',
            firstName: 'Susan',
            firstLastName: 'Li',
            email: 'susan.li@meta.com',
            avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-6.webp',
            isActive: true,
          }
        ],
        children: [
          {
            id: '15',
            positionId: 'pos-fin-analyst-001',
            name: 'Financial Analyst',
            positionCode: 'FIN-ANALYST',
            positionImage: null,
            organizationId: 'org-4',
            organizationName: 'Finance Division',
            organizationColor: '#4a90e2',
            functionalArea: 'Finance & Operations',
            location: 'sede-principal',
            hierarchicalLevel: 'operativo',
            requiredEmployees: 4,
            vacancies: 1,
            
            parentPositionId: '14',
            parentPositionName: 'Chief Financial Officer',
            
            description: 'Analyzes financial data and prepares reports',
            skills: ['Financial Modeling', 'Excel', 'SQL', 'Data Visualization'],
            isManagerial: false,
            assignedEmployees: [
              {
                id: 'emp-31',
                firstName: 'Robert',
                firstLastName: 'Walker',
                email: 'robert.walker@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-7.webp',
                isActive: true,
              },
              {
                id: 'emp-32',
                firstName: 'Karen',
                firstLastName: 'Hall',
                email: 'karen.hall@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-8.webp',
                isActive: true,
              },
              {
                id: 'emp-33',
                firstName: 'Thomas',
                firstLastName: 'Allen',
                email: 'thomas.allen@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-9.webp',
                isActive: true,
              }
            ],
            children: undefined,
          }
        ],
      },
      {
        id: '16',
        positionId: 'pos-cmo-001',
        name: 'Chief Marketing Officer',
        positionCode: 'CMO',
        positionImage: null,
        organizationId: 'org-5',
        organizationName: 'Marketing Division',
        organizationColor: '#e91e63',
        functionalArea: 'Marketing & Communications',
        location: 'sucursal-sur',
        hierarchicalLevel: 'alta_direccion',
        requiredEmployees: 1,
        vacancies: 0,
        
        parentPositionId: '1',
        parentPositionName: 'Chief Executive Officer',
        
        description: 'Leads global marketing strategy and brand management',
        skills: ['Brand Strategy', 'Digital Marketing', 'Campaign Management', 'Market Research'],
        isManagerial: true,
        assignedEmployees: [
          {
            id: 'emp-34',
            firstName: 'Alex',
            firstLastName: 'Schultz',
            email: 'alex.schultz@meta.com',
            avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-10.webp',
            isActive: true,
          }
        ],
        children: [
          {
            id: '17',
            positionId: 'pos-mkt-mgr-001',
            name: 'Marketing Manager',
            positionCode: 'MKT-MGR',
            positionImage: null,
            organizationId: 'org-5',
            organizationName: 'Marketing Division',
            organizationColor: '#e91e63',
            functionalArea: 'Marketing & Communications',
            location: 'sucursal-centro',
            hierarchicalLevel: 'ejecutivo',
            requiredEmployees: 3,
            vacancies: 0,
            
            parentPositionId: '16',
            parentPositionName: 'Chief Marketing Officer',
            
            description: 'Manages marketing campaigns and initiatives',
            skills: ['Campaign Strategy', 'Content Marketing', 'Social Media', 'Analytics'],
            isManagerial: true,
            assignedEmployees: [
              {
                id: 'emp-35',
                firstName: 'Emma',
                firstLastName: 'Young',
                email: 'emma.young@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-11.webp',
                isActive: true,
              },
              {
                id: 'emp-36',
                firstName: 'Matthew',
                firstLastName: 'King',
                email: 'matthew.king@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-12.webp',
                isActive: true,
              },
              {
                id: 'emp-37',
                firstName: 'Olivia',
                firstLastName: 'Wright',
                email: 'olivia.wright@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-13.webp',
                isActive: true,
              }
            ],
            children: undefined,
          }
        ],
      },
      {
        id: '18',
        positionId: 'pos-chro-001',
        name: 'Chief Human Resources Officer',
        positionCode: 'CHRO',
        positionImage: null,
        organizationId: 'org-1',
        organizationName: 'Meta Headquarters',
        organizationColor: '#1877f2',
        functionalArea: 'Human Resources',
        location: 'sede-remota',
        hierarchicalLevel: 'alta_direccion',
        requiredEmployees: 1,
        vacancies: 0,
        
        parentPositionId: '1',
        parentPositionName: 'Chief Executive Officer',
        
        description: 'Leads talent acquisition, development, and organizational culture',
        skills: ['Talent Management', 'Organizational Development', 'Culture Building', 'Compensation'],
        isManagerial: true,
        assignedEmployees: [
          {
            id: 'emp-38',
            firstName: 'Lori',
            firstLastName: 'Goler',
            email: 'lori.goler@meta.com',
            avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-14.webp',
            isActive: true,
          }
        ],
        children: [
          {
            id: '19',
            positionId: 'pos-recruiter-001',
            name: 'Technical Recruiter',
            positionCode: 'RECRUITER',
            positionImage: null,
            organizationId: 'org-1',
            organizationName: 'Meta Headquarters',
            organizationColor: '#1877f2',
            functionalArea: 'Human Resources',
            location: 'sede-remota',
            hierarchicalLevel: 'operativo',
            requiredEmployees: 5,
            vacancies: 2,
            
            parentPositionId: '18',
            parentPositionName: 'Chief Human Resources Officer',
            
            description: 'Recruits top technical talent for engineering roles',
            skills: ['Technical Recruiting', 'Interviewing', 'Candidate Assessment', 'Networking'],
            isManagerial: false,
            assignedEmployees: [
              {
                id: 'emp-39',
                firstName: 'Hannah',
                firstLastName: 'Scott',
                email: 'hannah.scott@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-15.webp',
                isActive: true,
              },
              {
                id: 'emp-40',
                firstName: 'Nathan',
                firstLastName: 'Green',
                email: 'nathan.green@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-16.webp',
                isActive: true,
              },
              {
                id: 'emp-41',
                firstName: 'Samantha',
                firstLastName: 'Baker',
                email: 'samantha.baker@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-17.webp',
                isActive: true,
              }
            ],
            children: undefined,
          },
          {
            id: '20',
            positionId: 'pos-hr-coord-001',
            name: 'HR Coordinator',
            positionCode: 'HR-COORD',
            positionImage: null,
            organizationId: 'org-1',
            organizationName: 'Meta Headquarters',
            organizationColor: '#1877f2',
            functionalArea: 'Human Resources',
            location: 'sede-remota',
            hierarchicalLevel: 'Auxiliar',
            requiredEmployees: 3,
            vacancies: 1,
            
            parentPositionId: '18',
            parentPositionName: 'Chief Human Resources Officer',
            
            description: 'Provides administrative support for HR operations',
            skills: ['HR Administration', 'Employee Onboarding', 'HRIS', 'Communication'],
            isManagerial: false,
            assignedEmployees: [
              {
                id: 'emp-42',
                firstName: 'Grace',
                firstLastName: 'Adams',
                email: 'grace.adams@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-18.webp',
                isActive: true,
              },
              {
                id: 'emp-43',
                firstName: 'Tyler',
                firstLastName: 'Nelson',
                email: 'tyler.nelson@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-19.webp',
                isActive: true,
              }
            ],
            children: undefined,
          }
        ],
      },
      {
        id: '21',
        positionId: 'pos-clo-001',
        name: 'Chief Legal Officer',
        positionCode: 'CLO',
        positionImage: null,
        organizationId: 'org-6',
        organizationName: 'Legal Division',
        organizationColor: '#9c27b0',
        functionalArea: 'Legal & Compliance',
        location: 'sede-remota',
        hierarchicalLevel: 'alta_direccion',
        requiredEmployees: 1,
        vacancies: 0,
        
        parentPositionId: '1',
        parentPositionName: 'Chief Executive Officer',
        
        description: 'Oversees legal affairs, compliance, and regulatory matters',
        skills: ['Corporate Law', 'Regulatory Compliance', 'Privacy Law', 'Contract Negotiation'],
        isManagerial: true,
        assignedEmployees: [
          {
            id: 'emp-44',
            firstName: 'Jennifer',
            firstLastName: 'Newstead',
            email: 'jennifer.newstead@meta.com',
            avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-20.webp',
            isActive: true,
          }
        ],
        children: [
          {
            id: '22',
            positionId: 'pos-corp-counsel-001',
            name: 'Corporate Counsel',
            positionCode: 'COUNSEL',
            positionImage: null,
            organizationId: 'org-6',
            organizationName: 'Legal Division',
            organizationColor: '#9c27b0',
            functionalArea: 'Legal & Compliance',
            location: 'sede-remota',
            hierarchicalLevel: 'ejecutivo',
            requiredEmployees: 4,
            vacancies: 1,
            
            parentPositionId: '21',
            parentPositionName: 'Chief Legal Officer',
            
            description: 'Provides legal counsel on corporate matters',
            skills: ['Contract Law', 'Intellectual Property', 'Litigation', 'Legal Research'],
            isManagerial: false,
            assignedEmployees: [
              {
                id: 'emp-45',
                firstName: 'William',
                firstLastName: 'Carter',
                email: 'william.carter@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-21.webp',
                isActive: true,
              },
              {
                id: 'emp-46',
                firstName: 'Victoria',
                firstLastName: 'Mitchell',
                email: 'victoria.mitchell@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-22.webp',
                isActive: true,
              },
              {
                id: 'emp-47',
                firstName: 'Benjamin',
                firstLastName: 'Perez',
                email: 'benjamin.perez@meta.com',
                avatarUrl: 'https://api-prod-minimal-v700.pages.dev/assets/images/avatar/avatar-23.webp',
                isActive: true,
              }
            ],
            children: undefined,
          }
        ],
      }
    ],
  },
  totalPositions: 22,
  totalEmployees: 47,
  totalVacancies: 16,
  maxDepth: 5,
  organizations: [
    { id: 'org-1', name: 'Meta Headquarters', color: '#1877f2' },
    { id: 'org-2', name: 'Engineering Division', color: '#00a400' },
    { id: 'org-3', name: 'Product Division', color: '#ff6b35' },
    { id: 'org-4', name: 'Finance Division', color: '#4a90e2' },
    { id: 'org-5', name: 'Marketing Division', color: '#e91e63' },
    { id: 'org-6', name: 'Legal Division', color: '#9c27b0' },
  ],
  functionalAreas: [
    'Executive Leadership',
    'Engineering & Technology',
    'Infrastructure Engineering',
    'AI & Machine Learning',
    'Product Engineering',
    'Product Management',
    'Finance & Operations',
    'Marketing & Communications',
    'Human Resources',
    'Legal & Compliance'
  ],
};